service:
  name: ott-training-crud
  disabledDeprecations:
  - CODE_1 # To disable specific deprecation with code "CODE_1"
  - "*" # To disable all deprecation messages
plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

custom:
  settings:
    POSTS_TABLE: s-ott-crud
  bundle:
    linting: false

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.settings.POSTS_TABLE}"

functions:
  name:
    handler: src/handlers/name.handler
    events:
      - http:
          method: POST
          path: /name
  hello:
    handler: src/handlers/hello.handler
    events:
      - http:
          method: GET
          path: /hello
          
resources:
  Resources:
    PostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.settings.POSTS_TABLE}
